
import { Poppins } from 'next/font/google'
import './globals.css'
import NavBar from '@/components/NavBar'
import axios from 'axios'
const inter = Poppins({ subsets: ['latin'] , weight: '500' } )

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <NavBar/>

      {children}
      </body>
      
    </html>
  )
}
